language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t fernandovarella/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fernandovarella/react-test npm test -- --coverage

after_success:
  - docker build -t fernandovarella/multi-client ./client
  - docker build -t fernandovarella/multi-nginx ./nginx
  - docker build -t fernandovarella/multi-server ./server
  - docker build -t fernandovarella/multi-worker ./worker
  # Login on docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images
  - docker push fernandovarella/multi-client
  - docker push fernandovarella/multi-nginx
  - docker push fernandovarella/multi-server
  - docker push fernandovarella/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-387149904661
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY